name: go test & go build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: go test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test Token
      run: go test ./token/
      working-directory: ./jackanalyzer
    
    - name: Test Tokenizer
      run: go test ./tokenizer/
      working-directory: ./jackanalyzer
    
    - name: Test CompilationEngine
      run: go test ./cmplengn
      working-directory: ./jackanalyzer

  build:
    name: go build
    runs-on: ubuntu-latest
    needs: test
    env:
      DOCKER_BUILDKIT: 1
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build macOS
      run: make PLATFORM=darwin/amd64
